version: '3.8'
services:
  jenkins-controller:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-controller
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "JENKINS_OPTS=--prefix=/jenkins"
      - "JAVA_OPTS=-Djenkins.install.runSetupWizard=false"
    restart: unless-stopped

  jenkins-agent:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    container_name: jenkins-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_home:
